# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each 6 hours)
  schedule: [{cron: "0 0/6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v4
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: BirdeeHub
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "update metrics"
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          commits_authoring: BirdeeHub, Birdee

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_other: yes
          plugin_languages_colors: rainbow
          plugin_languages_sections: "recently-used,most-used"
          plugin_languages_details: "bytes-size,percentage,lines"
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: "data,markup,programming,prose"
          plugin_languages_recent_categories: "data,markup,programming,prose"
          plugin_languages_limit: 8
          plugin_stargazers: yes
          plugin_lines: yes
          plugin_lines_history_limit: 0
          plugin_stars: yes
          plugin_stars_limit: 2
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_followup: yes
          plugin_followup_sections: "repositories,user"
          plugin_followup_indepth: yes
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_limit_discussions: 1000
          plugin_reactions_limit_discussions_comments: 1000
          plugin_reactions_details: "count,percentage"
          plugin_repositories: yes
          plugin_repositories_pinned: 1
          plugin_repositories_random: 1
          plugin_repositories_affiliations: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_notable: yes
          plugin_notable_filter: "stars>=1000"
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_types: "commit,pull_request,issue"
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_traffic: yes
          plugin_code: yes
          plugin_code_visibility: public
          plugin_code_languages: go,bash,kotlin,java,lua,nix
          plugin_introduction: yes
          plugin_pagespeed: no
          plugin_pagespeed_url: "https://nixcats.org"
          plugin_fortune: yes
